
dist: trusty
language: java
jdk:
  - openjdk11

# http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false

addons:
  apt:
    packages:
      - tree

before_install:
  - rvm install 2.2.5
  - rvm use 2.2.5
  - bin/build-jq.sh  # we want jq 1.5 features; not avail through pkg repo.

# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true  # if we don't skip install, ./gradlew assemble is invoked, but this task is not available.
env:
    - ANDROID_HOME=$HOME/android-sdk

script:
    - ./gradlew clean build 
